runtime: python39

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
